---
- name: Install Apache
  apt:
    name: "{{ apache_packages }}"
    state: present
    update_cache: true

- name: Enable Apache modules
  apache2_module:
    state: present
    name: php*

- name: Ensure Apache running
  service:
    name: apache2
    state: started
    enabled: true
