mysql_port: 3306
mysql_bind_address: "0.0.0.0"
mysql_package_name: mysql-server
client_package_name: mysql-client
python_mysql_dependency: python3-pymysql # Wymagane przez Ansible do zarządzania bazą
