---
- name: Install MySQL Server
  apt:
    name: ["mariadb-server"]
    state: present
    update_cache: yes

- name: Ensure MySQL running
  service:
    name: mariadb
    state: started
    enabled: true

- name: Set MySQL root password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create database
  mysql_db:
    name: "{{ app_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create app user
  mysql_user:
    name: "{{ app_db_user }}"
    password: "{{ app_db_password }}"
    priv: "{{ app_db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
