---
- name: Create app directory
  file:
    path: "{{ app_dir }}"
    state: directory

- name: Deploy demo PHP app
  template:
    src: index.php.j2
    dest: "{{ app_dir }}/index.php"
    mode: 0644
